{{- if eq .Values.mode "service" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nospy.fullname" . }}
  labels:
    {{- include "nospy.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
